import type { Chat, Message, User } from "./types"

export const currentUser: User = {
  id: "user-1",
  name: "You",
  avatar: undefined,
  online: true,
}

export const mockUsers: User[] = [
  {
    id: "user-2",
    name: "Sarah Chen",
    online: true,
  },
  {
    id: "user-3",
    name: "Alex Johnson",
    online: false,
    lastSeen: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: "user-4",
    name: "Design Team",
    online: true,
  },
  {
    id: "user-5",
    name: "Mike Wilson",
    online: false,
    lastSeen: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: "user-6",
    name: "Emma Davis",
    online: true,
  },
  {
    id: "user-7",
    name: "Project Updates",
    online: true,
  },
  {
    id: "user-8",
    name: "John Smith",
    online: false,
    lastSeen: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
  {
    id: "user-9",
    name: "Tech News",
    online: true,
  },
]

export const mockChats: Chat[] = [
  {
    id: "chat-1",
    type: "private",
    name: "Sarah Chen",
    participants: [currentUser, mockUsers[0]],
    lastMessage: {
      id: "msg-1",
      chatId: "chat-1",
      senderId: "user-2",
      content: "Hey! Are you coming to the meeting?",
      timestamp: new Date(Date.now() - 1000 * 60 * 2),
      status: "read",
      type: "text",
    },
    unreadCount: 2,
    pinned: true,
  },
  {
    id: "chat-2",
    type: "group",
    name: "Design Team",
    participants: [currentUser, mockUsers[0], mockUsers[1], mockUsers[3]],
    lastMessage: {
      id: "msg-2",
      chatId: "chat-2",
      senderId: "user-4",
      content: "The new mockups are ready for review",
      timestamp: new Date(Date.now() - 1000 * 60 * 15),
      status: "delivered",
      type: "text",
    },
    unreadCount: 5,
    typing: ["Alex"],
  },
  {
    id: "chat-3",
    type: "private",
    name: "Alex Johnson",
    participants: [currentUser, mockUsers[1]],
    lastMessage: {
      id: "msg-3",
      chatId: "chat-3",
      senderId: "user-1",
      content: "Thanks for the update!",
      timestamp: new Date(Date.now() - 1000 * 60 * 45),
      status: "read",
      type: "text",
    },
    unreadCount: 0,
  },
  {
    id: "chat-4",
    type: "channel",
    name: "Project Updates",
    participants: [currentUser],
    lastMessage: {
      id: "msg-4",
      chatId: "chat-4",
      senderId: "user-7",
      content: "Sprint 5 has been completed successfully!",
      timestamp: new Date(Date.now() - 1000 * 60 * 60),
      status: "read",
      type: "text",
    },
    unreadCount: 0,
    muted: true,
  },
  {
    id: "chat-5",
    type: "private",
    name: "Mike Wilson",
    participants: [currentUser, mockUsers[3]],
    lastMessage: {
      id: "msg-5",
      chatId: "chat-5",
      senderId: "user-5",
      content: "Can you send me the files?",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
      status: "read",
      type: "text",
    },
    unreadCount: 0,
  },
  {
    id: "chat-6",
    type: "private",
    name: "Emma Davis",
    participants: [currentUser, mockUsers[4]],
    lastMessage: {
      id: "msg-6",
      chatId: "chat-6",
      senderId: "user-1",
      content: "See you tomorrow!",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
      status: "delivered",
      type: "text",
    },
    unreadCount: 0,
  },
  {
    id: "chat-7",
    type: "channel",
    name: "Tech News",
    participants: [currentUser],
    lastMessage: {
      id: "msg-7",
      chatId: "chat-7",
      senderId: "user-9",
      content: "New AI breakthrough announced today",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
      status: "read",
      type: "text",
    },
    unreadCount: 12,
  },
  {
    id: "chat-8",
    type: "private",
    name: "John Smith",
    participants: [currentUser, mockUsers[6]],
    lastMessage: {
      id: "msg-8",
      chatId: "chat-8",
      senderId: "user-8",
      content: "Let me know when you're free",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
      status: "read",
      type: "text",
    },
    unreadCount: 0,
  },
]

export const mockMessages: Record<string, Message[]> = {
  "chat-1": [
    {
      id: "m1-1",
      chatId: "chat-1",
      senderId: "user-2",
      content: "Hi there! How are you doing?",
      timestamp: new Date(Date.now() - 1000 * 60 * 60),
      status: "read",
      type: "text",
    },
    {
      id: "m1-2",
      chatId: "chat-1",
      senderId: "user-1",
      content: "Hey Sarah! I'm doing great, thanks for asking. Just finished the project we discussed.",
      timestamp: new Date(Date.now() - 1000 * 60 * 55),
      status: "read",
      type: "text",
    },
    {
      id: "m1-3",
      chatId: "chat-1",
      senderId: "user-2",
      content: "That's awesome! Can you share the details?",
      timestamp: new Date(Date.now() - 1000 * 60 * 50),
      status: "read",
      type: "text",
    },
    {
      id: "m1-4",
      chatId: "chat-1",
      senderId: "user-1",
      content: "Sure! I'll send over the documents shortly. We managed to complete all the milestones ahead of schedule.",
      timestamp: new Date(Date.now() - 1000 * 60 * 45),
      status: "read",
      type: "text",
    },
    {
      id: "m1-5",
      chatId: "chat-1",
      senderId: "user-2",
      content: "Perfect! The team will be thrilled to hear this.",
      timestamp: new Date(Date.now() - 1000 * 60 * 30),
      status: "read",
      type: "text",
    },
    {
      id: "m1-6",
      chatId: "chat-1",
      senderId: "user-2",
      content: "By the way, we have a sync meeting at 3 PM today.",
      timestamp: new Date(Date.now() - 1000 * 60 * 10),
      status: "read",
      type: "text",
    },
    {
      id: "m1-7",
      chatId: "chat-1",
      senderId: "user-2",
      content: "Hey! Are you coming to the meeting?",
      timestamp: new Date(Date.now() - 1000 * 60 * 2),
      status: "read",
      type: "text",
    },
  ],
  "chat-2": [
    {
      id: "m2-1",
      chatId: "chat-2",
      senderId: "user-3",
      content: "Hey team, I've updated the design system documentation.",
      timestamp: new Date(Date.now() - 1000 * 60 * 120),
      status: "read",
      type: "text",
    },
    {
      id: "m2-2",
      chatId: "chat-2",
      senderId: "user-5",
      content: "Great work Alex! I'll review it this afternoon.",
      timestamp: new Date(Date.now() - 1000 * 60 * 90),
      status: "read",
      type: "text",
    },
    {
      id: "m2-3",
      chatId: "chat-2",
      senderId: "user-1",
      content: "Thanks for the update. Let me know if you need any feedback.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60),
      status: "read",
      type: "text",
    },
    {
      id: "m2-4",
      chatId: "chat-2",
      senderId: "user-4",
      content: "The new mockups are ready for review",
      timestamp: new Date(Date.now() - 1000 * 60 * 15),
      status: "delivered",
      type: "text",
    },
  ],
  "chat-3": [
    {
      id: "m3-1",
      chatId: "chat-3",
      senderId: "user-3",
      content: "Hey, just wanted to give you a quick update on the backend changes.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
      status: "read",
      type: "text",
    },
    {
      id: "m3-2",
      chatId: "chat-3",
      senderId: "user-1",
      content: "Sure, what's new?",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1.5),
      status: "read",
      type: "text",
    },
    {
      id: "m3-3",
      chatId: "chat-3",
      senderId: "user-3",
      content: "We've migrated the database and improved query performance by 40%.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60),
      status: "read",
      type: "text",
    },
    {
      id: "m3-4",
      chatId: "chat-3",
      senderId: "user-1",
      content: "Thanks for the update!",
      timestamp: new Date(Date.now() - 1000 * 60 * 45),
      status: "read",
      type: "text",
    },
  ],
}
